<div class="box">
	<!-- Box Head -->
	<div class="box-head">
		<h2>Ghi Sổ Nợ</h2>
	</div>
	<!-- End Box Head-->
	<div class="box-content">
		<div class='table'>
			<form id='addhistoryid' action="/administrator/addhistory" method="post" enctype="application/x-www-form-urlencoded">
			<table>
				<tr>
					<td>Tên Đăng Nhập : </td>
					<td><?echo $this->formHidden('id',$this->id)?><?php echo $this->formText('username',$this->username,array('class'=>'button','style'=>'width:170px'))?></td>
					<td><?php echo $this->errorUsername;  ?></td>
				</tr>
				<tr>
					<td>Tên Khách Hàng : </td>
					<td><?php echo $this->formText('nickname',$this->nickname,array('class'=>'button','style'=>'width:170px'))?></td>
					<td><?php echo $this->errorNickname;  ?></td>
				</tr>
				<tr>
					<td>Sản Phẩm : </td>
					<td><?php echo $this->formSelect('product',((isset($this->select)? $this->select:1)),array('class'=>'button','style'=>'height:20px'),$this->arrproduct)?>&nbsp;&nbsp;<?php echo $this->formText('price',$this->price,array('class'=>'field','style'=>'width:50px;height:13px;text-align:right'))?>  <b>VNĐ</b></td>
					<td><?php echo $this->errorProduct;  ?></td>
				</tr>
				<tr>
					<td>Số Lượng :</td>
					<td><?php echo $this->formText('quantity',(isset($this->quantity))? $this->quantity:0,array('class'=>'field','style'=>'text-align:center;width:30px;'))?> Cái<font color="red"><b> *</b></font></td>
					<td><?php echo $this->errorQuantity;  ?></td>
				</tr>
				<tr>
					<td>Tổng Tiền :</td>
					<td><?php echo $this->formText('total',(isset($this->total))? $this->total:0,array('class'=>'field','style'=>'text-align:right;background:#cfcfcf;'))?> <b>VNĐ</b></td>
					<td><?php echo $this->errorTotal;  ?></td>
				</tr>
				<tr>
					<td>Tình Trạng : </td>
					<td><?php echo $this->formSelect('status',(isset($this->status))? $this->status:1,array('class'=>'button','style'=>'width:170px;color:red'),array(1=>'Chưa Thanh Toán',2=>'Đã Thanh Toán'))?></td>
					<td><?php echo $this->errorStatus;  ?></td>
				</tr>
				<tr>
					<td>Ghi chú :</td>
					<td><?php echo $this->formTextarea('description',(isset($this->description))? $this->description:'',array('class'=>'field','style'=>'width:190px;height:80px'))?></td>
					<td><?php echo $this->errorDescription;  ?></td>
				</tr>
				<tr>
					<td></td>
					<td><?php echo $this->formSubmit('themsanpham','Ghi vào sổ',array('class'=>'button'))?></td>
					<td></td>
				</tr>
			</table>
			</form>
		</div>
	</div>
</div>

<script type="text/javascript">
$(document).ready(function() {
	$('#quantity').change(function() {
		var quantity = $('#quantity').val();
		var price = $('#price').val();
		$("#total").val(quantity*price);
	});
	$('#product').change(function(){
		$('#addhistoryid').submit();
	});
	
});
</script>
<!-- End Box -->
