
<div class="box">
	<!-- Box Head -->
	<div class="box-head">
		<h2>Thêm Sản Phẩm</h2>
	</div>
	<!-- End Box Head-->
	<div class="box-content">
		<div class='table'>
			<form action="/administrator/createproduct" method="post" enctype="application/x-www-form-urlencoded">
			<table>
				<tr>
					<td>Tên Sản Phẩm : </td>
					<td><?php echo $this->formText('name',$this->name,array('class'=>'field',))?><font color="red"> <b>*</b></font></td>
					<td><?php echo $this->errorName;  ?></td>
				</tr>
				<tr>
					<td>Giá thành : </td>
					<td><?php echo $this->formText('price',$this->price,array('class'=>'field','style'=>'text-align:right;'))?> VNĐ<font color="red"><b> *</b></font></td>
					<td><?php echo $this->errorPrice;  ?></td>
				</tr>
				<tr>
					<td>Thông Tin :</td>
					<td><?php echo $this->formTextarea('description',$this->description,array('class'=>'field','style' => 'width:250px;height:150px'))?><font color="red"> <b>*</b></font></td>
					<td><?php echo $this->errorDescription;  ?></td>
				</tr>
				<tr>
					<td></td>
					<td><?php echo $this->formSubmit('themsanpham','Thêm Sản Phẩm',array('class'=>'button'))?></td>
					<td></td>
				</tr>
			</table>
			</form>
		</div>
	</div>
</div>
<!-- End Box -->
