<!-- Box -->
<div class="box">

	<!-- Box Head -->
	<div class="box-head">
		<h2 class="left">Danh sách sản phẩm</h2>
		<div class="right">
			<label>Tìm kiếm </label>
			<input type="text" class="field small-field" />
			<input type="submit" class="button" value="Tìm" />
			<form action="/administrator/createproduct" method="get">
			</form>
		</div>
	</div>
	<!-- End Box Head -->	

	<!-- Table -->
	<div class="table">
		<table width="100%" border="0" cellspacing="0" cellpadding="0">
			<tr>
				<th width="13"><input type="checkbox" class="checkbox" /></th>
				<th>Id</th>
				<th>Tên Sản Phẩm</th>
				<th>Giá Tiền</th>
				<th>Thông Tin</th>
				<th width="110" class="ac">Content Control</th>
			</tr>
			<?php foreach ($this->listProduct as $value){ ?>
			<tr>
				<td><input type="checkbox" class="checkbox" /></td>
				<td><a href="#"><?= $value->zin_product_id ?></a></td>
				<td><h3><b><?= $value->zin_product_name ?></b></h3></td>
				<td align="right"><?= Zincome_Static::getCurrency($value->zin_product_price) ?></td>
				<td><?= $value->zin_product_description ?></td>
				<td><a href="#" class="ico del">Delete</a><a href="#" class="ico edit">Edit</a></td>
			</tr>
			<?php }?>
		</table>
		
		<!-- Pagging -->
		<div class="pagging">
			<div class="left">Đang xem 1-12 của 44</div>
			<div class="right">
				<a href="#">Trước</a>
				<a href="#">1</a>
				<a href="#">2</a>
				<a href="#">3</a>
				<a href="#">4</a>
				<a href="#">245</a>
				<span>...</span>
				<a href="#">Tiếp</a>
				<a href="#">Xem tất cả</a>
			</div>
		</div>
		<!-- End Pagging -->
		
	</div>
	<!-- Table -->
</div>
<!-- End Box -->