<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<title><?php echo $this->Title ?></title>
	<?php echo $this->Style ?>
	<?php echo $this->partial("partials/header.phtml") ?>
</head>
<body>
<!-- Header -->
<div id="header">
	<!-- bla bla -->
	<div id="basic-modal-content" class="boxxemthongtin"></div>
	<div id="basic-modal-content" class="boxdangkytaikhoan">
	
	</div>
	<!-- end bla bla -->
	<div class="shell">
		<!-- Logo + Top Nav -->
		<div id="top">
			<h1><img  src="/css/images/White Book.png" /><a href="#"><p style="margin-top:-28px;margin-left:35px">Nhà May Minh Nguyệt </p></a></h1>
			<?php  echo $this->partial("partials/top.phtml")?>
		</div>
		<!-- End Logo + Top Nav -->
		
		<!-- Main Nav -->
		<div id="navigation">
			<?php echo $this->partial("partials/menu.phtml") ?>
		</div>
		<!-- End Main Nav -->
	</div>
</div>
<!-- End Header -->

<!-- Container -->
<div id="container">
	<div class="shell">
		
		<!-- Small Nav -->
		<div class="small-nav">
		    <?php echo $this->partial("partials/navigation.phtml")?>
		</div>
		<!-- End Small Nav -->
		
		
		<!-- Main -->
		<div id="main">
			<div class="cl">&nbsp;</div>
			
			<!-- Content -->
			<div id="content">
            <?php echo $this->layout()->content; ?>
			</div>
			<!-- End Content -->
			
			<!-- Sidebar -->
			<div id="sidebar">
				<!-- Box -->
                <div class="box">
                	
                	<!-- Box Head -->
                	<div class="box-head">
                		<h2>Thanh Công Cụ</h2>
                	</div>
                	<!-- End Box Head-->
                	
                	<div class="box-content">
                		<a href="/administrator/createproduct" class="add-button" id="create-history" ><span style="width:70px">Sản Phẩm</span></a><br/><br/>
                		<a href="/administrator/registercustomer" class="add-button" id="register-khachhang" ><span style="width:70px">Khách Hàng</span></a>
                		<div class="cl">&nbsp;</div>
                	</div>
                </div>
                
                <!-- End Box -->
				
			</div>
			<!--x End Sidebar -->
			
			<div class="cl">&nbsp;</div>			
		</div>
		<!-- Main -->
	</div>
</div>
<!-- End Container -->

<!-- Footer -->
<div id="footer">
	<div class="shell">
		<span class="left">&copy; 2011 - DEVEVELOPER BY SHI.NGUYENXUAN@GMAIL.COM</span>
		<span class="right">
			Design by <a href="/income/aboutus" target="_blank" title="">chocotemplates.com</a>
		</span>
	</div>
</div>
<!-- End Footer -->
</body>
</html>
