
<div class="box">
	<!-- Box Head -->
	<div class="box-head">
		<h2>Đăng nhập</h2>
	</div>
	<!-- End Box Head-->
	<div class="box-content">
		<div class='table'>
			<form action="/account/login" method="post" enctype="application/x-www-form-urlencoded">
			<table>
				<tr>
					<td>Tên đăng nhập : </td>
					<td><?php echo $this->formText('username',$this->username,array('class'=>'field',))?></td>
					<td><?php echo $this->errorUsername;  ?></td>
				</tr>
					
				<tr>
					<td>Mật khẩu :</td>
					<td><?php echo $this->formPassword('password',$this->password,array('class'=>'field'))?></td>
					<td><?php echo $this->errorPassword;  ?></td>
				</tr>
					
				<tr>
					<td></td>
					<td><?php echo $this->formSubmit('Login','Đăng nhập',array('class'=>'button'))?></td>
					<td></td>
				</tr>
			</table>
			</form>
		</div>
	</div>
</div>
<!-- End Box -->

<br>
<?php echo $this->loginfail ?>