<!-- Box -->
<div class="box"><!-- Box Head -->
<div class="box-head">
<h2 class="left">Danh sách sản phẩm</h2>
</div>
<?php 
    $date = Zend_Date::now();
    $getArr = Zincome_Static::getDaysMonth($date->get(Zend_Date::MONTH), 
    $date->get(Zend_Date::YEAR));
    $arr = Zincome_Date::getDaysToday_2(Zend_Date::now());    
?>
<table cellspacing="0">
	<thead>
		<tr>
			<th><input type="button" value="Trước" style="width:100%;height: 100%" /></th>
			<th></th>
			<th></th>
			<th><input type="button" value="<?php echo ucfirst($date->get(Zend_Date::MONTH_NAME,'vi'))?>" style="width:100%;height: 100%" /></th>
			<th></th>
			<th></th>
			<th><input type="button" value="Trước" style="width:100%;height: 100%" /></th>
		</tr>
		<tr>
			<th>Chủ Nhật</th>
			<th>Thứ 2</th>
			<th>Thứ 3</th>
			<th>Thứ 4</th>
			<th>Thứ 5</th>
			<th>Thứ 6</th>
			<th>Thứ 7</th>
		</tr>
	</thead>
	<tbody>
	<?php
    foreach ($arr as $value) {
        echo '<tr>';
        foreach ($value as $key) {
            echo $key;
        }
         echo '</tr>';
    }
    ?>
	</tbody>
	<tfoot>
		<tr>
			<th>Chủ Nhật</th>
			<th>Thứ 2</th>
			<th>Thứ 3</th>
			<th>Thứ 4</th>
			<th>Thứ 5</th>
			<th>Thứ 6</th>
			<th>Thứ 7</th>
		</tr>
	</tfoot>
</table>

<!-- Table --></div>
<!-- End Box -->
<script src="/css/javascripts/coda.js"></script>