<!-- Box -->
<div class="box">

	<!-- Box Head -->
	<div class="box-head">
		<h2 class="left">Thống Kê Theo Ngày</h2>
		<div class="right">
			<label>Tìm kiếm </label>
			<input type="text" class="field small-field" />
			<input type="submit" class="button" value="Tìm" />
		</div>
	</div>
	<!-- End Box Head -->	

	<!-- Table -->
	<div class="table">
		<table width="100%" border="0" cellspacing="0" cellpadding="0">
			<tr>
				<th  width="10px">Id</th>
				<th>Tên khách hàng</th>
				<th>Thời Gian</th>
				<th>Sản phẩm</th>
				<th>Số lượng</th>
				<th>Tổng giá</th>
				<th>Tình trạng</th>
			</tr>
			<?php foreach ($this->listHistory as $value) {?>
			<tr>
				<td><?= $value->zin_history_id ?></td>
				<td>
					<font size=2><b><? $users = Zincome_Static::getUserByID($value->zin_user_ref);
						echo ($users->zin_user_nickname); 
					?></b></font>
				</td>
				<td><?php echo Zincome_Static::getDateTime($value->zin_history_time_updated)?></td>
				<td align="center">
					<? $product = Zincome_Static::getProductByID($value->zin_product_ref);
						echo ($product->zin_product_name);  ?>
				</td>
				<td align="center"><?= $value->zin_history_quantity ?></td>
				<td align="right"><?= Zincome_Static::getCurrency($value->zin_history_total) ?></td>
				<td><?= Zincome_Static::getTypeByInt($value->zin_history_type) ?></td>
				<td><?php if($value->zin_history_type == 1){?><a href="" class="changestatus" original-title="Chuyển sang trạng thái đã thanh toán"><img width="20px" src="/css/images/finished-red.png" /></a><?php }else{?><a href="" class="changestatus" original-title="Chuyển sang trạng thái chưa thanh toán"><img width="20px" src="/css/images/finished-green.png" /></a><?php }?></td>
				</tr>
			<?php }?>
		</table>
		
		
		<!-- Pagging -->
		<div class="pagging">
			<div class="left">Đang xem 1-12 của 44</div>
			<div class="right">
				<a href="#">Trước</a>
				<a href="#">1</a>
				<a href="#">2</a>
				<a href="#">3</a>
				<a href="#">4</a>
				<a href="#">245</a>
				<span>...</span>
				<a href="#">Tiếp</a>
				<a href="#">Xem tất cả</a>
			</div>
		</div>
		<!-- End Pagging -->
		
	</div>
	<!-- Table -->
	
</div>
<!-- End Box -->