<!-- End Message OK -->	
<!-- Message Error -->
<div class="msg msg-error"><p><strong>[ Lỗi 404 ] Trang không tồn tại !</strong></p><a href="#" class="close" original-title="Xóa thông báo này !">close</a></div>
<!-- End Message Error -->
<!-- Message OK -->		
<div class="msg msg-ok">
	<p><strong>Click vào <a href='/income/index'><font color="red">đây</font></a> để ra trang chủ !</strong></p>
	<a href="#" class="close" original-title="Xóa thông báo này !">close</a>
</div>
<!-- End Message OK -->	