<link rel="stylesheet" href="/css/style.css" type="text/css" media="all" />
<link rel="stylesheet" href="/css/tipsy.css" type="text/css" media="all" />
<script src="/css/javascripts/jquery-1.3.2.min.js"
	type="text/javascript"></script>
<script src="/css/javascripts/jquery.tipsy.js" type="text/javascript"></script>
<script type='text/javascript'> 
		$(function() {
//			$('.close').parent('div').hide('fast');
	    	$('.close').tipsy({gravity: 'e'});
	    	$('.close').click(function(){
	    		$(this).parent('div').fadeOut();
	    	});
	    	$('.showday').tipsy({gravity: 's'});
	    	$('.edit').tipsy({gravity: 'w'});
	    	$('.changestatus').tipsy({gravity: 'e'});
//	    	$('.xemthongtin').click(function (e) {
//	    	
//			});
//			
//			$('#register-khachhang').click(function(){
//			
//			});
	    	$(document).ready(function() {
	    	    var pathname = window.location.pathname;
	    	    if(pathname == '/income/index' || pathname == '/'){
		    	    $('#trangchu').addClass('active');
		    	    }
	    	    else if(pathname == '/administrator/customer'){
	    	    	$('#khachhang').addClass('active');
		    	    }
    	    	else if(pathname == '/administrator/revenue'){
   	    		 	$('#tongket').addClass('active');
        	    	}
    			else if(pathname == '/administrator/product'){
   				 	$('#sanpham').addClass('active');
        			}
    			else if(pathname == '/income/aboutus'){
   				 	$('#aboutus').addClass('active');
   				 	}
	    	});
	    	
	  	});
</script>