
<?php

$container = new Zend_Navigation();
$this->navigation($container);

$container->addPage(
    array
    (
    	'label' => 'Trang chủ',
    	'module' => 'default',
        'controller' => 'Income',
        'action'     => 'index',
        'pages'      =>array
        (    array
            (
            	'label' => 'Thống Kê',
                'controller' => 'income',
                'action'     => 'index',
                'pages'      =>array
                (
                     
                )
            ),
            array
            (
            	'label' => 'Tổng Kết',
                'controller' => 'income',
                'action'     => 'index',
                'pages'      =>array
                (
                    
                )
            ),
            array
            (
            	'label' => 'Sản Phẩm',
                'controller' => 'income',
                'action'     => 'product',
                'pages'      =>array
                (
                
                )
            ),
            array
            (
            	'label' => 'Tài Khoản',
                'controller' => 'account',
                'action'     => 'index',
                'pages'      =>array
                (
                    array
                    (
                    	'label' => 'Đăng Ký',
                        'controller' => 'account',
                        'action'     => 'register',
                        'pages'      =>array
                        (
                            
                        )
                    ),
                    array
                    (
                    	'label' => 'Đăng Nhập',
                        'controller' => 'account',
                        'action'     => 'login',
                        'pages'      =>array
                        (
                            array
                            (
                            	'label' => 'Thông Báo',
                                'controller' => 'account',
                                'action'     => 'loginfinish',
                                'pages'      =>array
                                (
                                    
                                )
                            )
                        )
                    ),
                    array
                    (
                    	'label' => 'Thoát',
                        'controller' => 'account',
                        'action'     => 'logout',
                        'pages'      =>array
                        (
                            
                        )
                    )
                    
                    
                )
            ),array
            (
            	'label' => 'Quản Lý',
                'controller' => 'administrator',
                'action'     => 'index',
                'pages'      =>array
                (
                    array
                    (
                    	'label' => 'Khách Hàng',
                        'controller' => 'administrator',
                        'action'     => 'customer',
                        'pages'      =>array
                        (
                            array
                    (
                    	'label' => 'Tạo Khách Hàng',
                        'controller' => 'administrator',
                        'action'     => 'registercustomer',
                        'pages'      =>array
                        (
                             array
                            (
                            	'label' => 'Tạo khách hàng thành công',
                                'controller' => 'administrator',
                                'action'     => 'registerfinish',
                                'pages'      =>array
                                (
                                
                                )
                            )
                        )
                    )
                        )
                    ),
                    array
                    (
                    	'label' => 'Tổng Kết Doanh Thu',
                        'controller' => 'administrator',
                        'action'     => 'revenue',
                        'pages'      =>array
                        (
                            
                        )
                    ),
                    array
                    (
                    	'label' => 'Sản Phẩm',
                        'controller' => 'administrator',
                        'action'     => 'product',
                        'pages'      =>array
                        (
                            
                        )
                    )
                )
            ),array
                    (
                    	'label' => 'Thông Tin Trang Web',
                        'controller' => 'income',
                        'action'     => 'aboutus'
                        )
            
        )
    )
);
 
echo $this->navigation()->breadcrumbs()->setPartial('partials/breadcrumbs.phtml')->setLinkLast(false)->setMinDepth(0);

?>