<!-- Message OK -->		
<div class="msg msg-ok">
	<p><strong>File của bạn đã upload thành công !</strong></p>
	<a href="#" class="close" original-title="Xóa thông báo này !">close</a>
</div>
<!-- End Message OK -->	
<!-- Message Error -->
<div class="msg msg-error"><p><strong>Bạn cần chọn file upload !</strong></p><a href="#" class="close" original-title="Xóa thông báo này !">close</a></div>
<!-- End Message Error -->