<div class="box">
	<!-- Box Head -->
	<div class="box-head">
		<h2 class="left">Đăng ký khách hàng</h2>
	</div>
	<!-- End Box Head -->	
	<!-- Table -->
	<div class="table">
		<table width="100%"  cellspacing="0" cellpadding="0">
			<tr >
				<td style="font-size:20px;color:#63291b" align="right">Tên khách hàng</td>
				<td style="border-left:1px solid #e0e0e0;" ><input style="font-size:20px" type="text" class="button xemthongtin" value="" /></th>
			</tr>
			<tr>
				<td style="font-size:20px;color:#63291b" align="right">Tên ký danh</td>
				<td style="border-left:1px solid #e0e0e0;"><input style="font-size:20px" type="text" class="button xemthongtin" value="" /></th>
			</tr>
			<tr>
				<td style="font-size:20px;color:#63291b" align="right">Số điện thoại</td>
				<td style="border-left:1px solid #e0e0e0;"><input style="font-size:20px" type="text" class="button xemthongtin" value="" /></th>
			</tr>
			<tr>
				<td style="font-size:20px;color:#63291b" align="right" valign="top">Địa chỉ</td>
				<td style="border-left:1px solid #e0e0e0;"><textarea style="font-size:20px;width:380px;Height:120px;" class="button" ></textarea></th>
			</tr>
			<tr>
				<td style="font-size:20px;color:#63291b"></td>
				<td style="border-left:1px solid #e0e0e0;"><a href="#" class="add-button" style="color:black;" ><span>Thêm Khách Hàng</span></a></th>
			</tr>
		</table>
	</div>
	<!-- Table -->
</div>